---

swagger: '2.0'

info:
  version: 0.1.0
  title: Simple To Do List API

basePath: /api

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

tags:
  - name: items
    description: To do list items

paths:
  /:
    get:
      summary: Get all items
      tags:
        - items
      operationId: find
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    post:
      summary: Create an item
      tags:
        - items
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        '201':
          description: Created
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - name: id
        in: path
        type: integer
        format: int64
        required: true
    get:
      summary: Get an item
      tags:
        - items
      operationId: getOne
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    put:
      summary: Update an item
      tags:
        - items
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      summary: Delete an item
      tags:
        - items
      operationId: destroyOne
      responses:
        '204':
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
        default: false
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
